# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_article_image_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
