# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170508_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='article',
        ),
        migrations.AddField(
            model_name='message',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
